### ISSUE TITLE
Startup failed on version of  1.9.1 and 1.9.2

### ISSUE THREAD

**Issue by quemilk** [AzulSystems/opthub-helm-charts#2]
<img width="981" alt="image" src="https://github.com/AzulSystems/opthub-helm-charts/assets/4969382/3cbd6f82-eb28-4fc8-8844-dbf332c99a0e">

**Comment by vladykin** [comment]
This happens when there is a mismatch between the helm chart version and the docker image version. These two versions must match exactly.

When installing the helm chart, only specify the `--version ...` flag to set the helm chart version, which pulls the matching docker image version automatically.

Using `--set version=...`, which overrides the docker image version from the helm chart, is not supported and will lead to various problems.
